# Generated by Django 5.0.14 on 2025-05-11 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DeskHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("id_flashcard", models.CharField(max_length=1000)),
                ("id_topic", models.CharField(max_length=1000)),
                ("status", models.CharField(max_length=1000)),
            ],
        ),
    ]
