# Generated by Django 5.2.7 on 2025-10-09 06:00

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("learn_history", "0001_initial"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="deskhistory",
            unique_together={("id_flashcard", "id_topic")},
        ),
    ]
