# Generated by Django 5.2 on 2025-05-03 03:35

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("knowledge_graph", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="graph",
            name="topic",
        ),
        migrations.RemoveField(
            model_name="graphrelationship",
            name="graph",
        ),
        migrations.DeleteModel(
            name="GraphNode",
        ),
        migrations.DeleteModel(
            name="Graph",
        ),
        migrations.DeleteModel(
            name="GraphRelationship",
        ),
    ]
