# Generated by Django 5.2 on 2025-05-03 03:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("flashcards", "0002_topic_store_id"),
        (
            "knowledge_graph",
            "0002_remove_graph_topic_remove_graphrelationship_graph_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="Graph",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "topic",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="graph",
                        to="flashcards.topic",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="GraphNode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("node_id", models.CharField(max_length=100)),
                ("label", models.CharField(max_length=100)),
                ("name", models.TextField()),
                (
                    "graph",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="nodes",
                        to="knowledge_graph.graph",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="GraphRelationship",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("type", models.CharField(max_length=100)),
                ("start_node_id", models.CharField(max_length=100)),
                ("end_node_id", models.CharField(max_length=100)),
                ("details", models.TextField()),
                (
                    "graph",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="relationships",
                        to="knowledge_graph.graph",
                    ),
                ),
            ],
        ),
    ]
