# Generated by Django 5.2 on 2025-05-03 08:19

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("knowledge_graph", "0003_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="graphnode",
            name="node_id",
        ),
        migrations.RemoveField(
            model_name="graphrelationship",
            name="details",
        ),
    ]
