# Generated by Django 5.2 on 2025-05-01 08:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("flashcards", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="topic",
            name="store_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
